---
apiVersion: v2
name: azimuth-identity-operator
description: Helm chart for deploying the Azimuth identity operator.
type: application
# The version and appVersion are updated by the chart build script
version: 0.1.0
appVersion: main
