apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "azimuth-identity-operator.fullname" . }}
  labels: {{ include "azimuth-identity-operator.labels" . | nindent 4 }}
rules:
  # Manipulating CRDs (only allow patching of our own CRDs)
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
      - get
      - watch
      - create
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - realms.identity.azimuth.stackhpc.com
      - clientregistrationtokens.identity.azimuth.stackhpc.com
    verbs:
      - update
      - patch
  # Required for kopf to watch resources properly
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
      - watch
  # Required for kopf to produce events properly
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
  # We can manipulate our own objects
  - apiGroups:
      - identity.azimuth.stackhpc.com
    resources:
      - "*"
    verbs:
      - "*"
  # We need to be able to manipulate secrets for tokens and Dex config
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "*"
  # We need to be able to manipulate the resources created for Dex instances
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - networkpolicies
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - "*"
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - "*"
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - role
      - rolebinding
      - clusterrole
      - clusterrolebinding
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - services
      - serviceaccounts
    verbs:
      - "*"
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - "*"
