{{- if and .Values.metrics.enabled .Values.metrics.dashboard.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "azimuth-identity-operator.fullname" . }}-dashboards
  labels:
    {{- include "azimuth-identity-operator.labels" . | nindent 4 }}
    {{- toYaml .Values.metrics.dashboard.labels | nindent 4 }}
data:
  azimuth_identity_dashboard.json: |
    {{- .Files.Get "files/grafana_dashboard.json" | nindent 4 }}
{{- end }}
