apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azimuth-identity-operator.fullname" . }}
  labels: {{ include "azimuth-identity-operator.labels" . | nindent 4 }}
stringData:
  identity-operator.yaml: |
    !include "/etc/azimuth/defaults.yaml,/etc/azimuth/user-config.yaml"
  defaults.yaml: |
    easykubeFieldManager: {{ include "azimuth-identity-operator.fullname" . }}
    {{- if .Values.tls.enabled }}
    dex:
      tlsSecret:
        name: {{ include "azimuth-identity-operator.tlsSecretName" . }}
        namespace: {{ .Release.Namespace }}
    {{- end }}
  user-config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
