name: Test Azimuth deployment

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
    branches:
      - main

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  # This job exists so that PRs from outside the main repo are rejected
  fail_on_remote:
    runs-on: ubuntu-latest
    steps:
      - name: PR must be from a branch in the stackhpc/azimuth-identity-operator repo
        run: exit ${{ github.repository == 'stackhpc/azimuth-identity-operator' && '0' || '1' }}

  publish_artifacts:
    needs: [fail_on_remote]
    uses: ./.github/workflows/build-push-artifacts.yaml

  run_azimuth_tests:
    needs: [publish_artifacts]
    runs-on: ubuntu-latest
    steps:
      # Check out the configuration repository
      - name: Set up Azimuth environment
        uses: stackhpc/azimuth-config/.github/actions/setup@main
        with:
          os-clouds: ${{ secrets.OS_CLOUDS }}
          environment-prefix: identity-ci
          extra-vars: |
            azimuth_identity_operator_chart_version: ${{ needs.publish_artifacts.outputs.chart-version }}

      # Provision Azimuth using the azimuth-ops version under test
      - name: Provision Azimuth
        uses: stackhpc/azimuth-config/.github/actions/provision@main

      # # Run the tests
      - name: Run Azimuth tests
        uses: stackhpc/azimuth-config/.github/actions/test@main

      # Tear down the environment
      - name: Destroy Azimuth
        uses: stackhpc/azimuth-config/.github/actions/destroy@main
        if: ${{ always() }}
