# This workflow proposes updates to the dependencies that dependabot cannot
name: Update dependencies

on:
  # Allow manual executions
  workflow_dispatch:
  # Run nightly
  schedule:
    - cron: '0 0 * * *'

jobs:
  propose_helm_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Check for most recent Helm version
        id: next
        uses: azimuth-cloud/github-actions/github-latest-release@master
        with:
          repository: helm/helm

      - name: Update dependency key
        uses: azimuth-cloud/github-actions/config-update@master
        with:
          path: ./Dockerfile
          updates: |
            HELM_VERSION=${{ steps.next.outputs.version }}

      - name: Generate app token for PR
        uses: azimuth-cloud/github-actions/generate-app-token@master
        id: generate-app-token
        with:
          repository: ${{ github.repository }}
          app-id: ${{ secrets.AUTOMATION_APP_ID }}
          app-private-key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}

      - name: Propose changes via PR if required
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-app-token.outputs.token }}
          commit-message: >-
            Update Helm to ${{ steps.next.outputs.version }}
          branch: update-dependency/helm
          delete-branch: true
          title: >-
            Update Helm to ${{ steps.next.outputs.version }}
          body: >
            This PR was created automatically to update
            Helm to ${{ steps.next.outputs.version }}.
          labels: |
            automation
            dependency-update

  propose_helm_chart_updates:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # The baked in Dex chart
          - key: dex
            path: ./Dockerfile
            chart_name_jsonpath: DEX_CHART_NAME
            chart_repo_jsonpath: DEX_CHART_REPO
            chart_version_jsonpath: DEX_CHART_VERSION

    name: ${{ matrix.key }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Extract repo and chart
        id: chart-info
        uses: azimuth-cloud/github-actions/config-extract@master
        with:
          path: ${{ matrix.path }}
          outputs: |
            repo=${{ matrix.chart_repo_jsonpath }}
            name=${{ matrix.chart_name_jsonpath }}

      - name: Check for updates
        id: next
        uses: azimuth-cloud/github-actions/helm-latest-version@master
        with:
          repository: ${{ steps.chart-info.outputs.repo }}
          chart: ${{ steps.chart-info.outputs.name }}

      - name: Update chart version
        uses: azimuth-cloud/github-actions/config-update@master
        with:
          path: ${{ matrix.path }}
          updates: |
            ${{ matrix.chart_version_jsonpath }}=${{ steps.next.outputs.version }}

      - name: Generate app token for PR
        uses: azimuth-cloud/github-actions/generate-app-token@master
        id: generate-app-token
        with:
          repository: ${{ github.repository }}
          app-id: ${{ secrets.AUTOMATION_APP_ID }}
          app-private-key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}

      - name: Propose changes via PR if required
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-app-token.outputs.token }}
          commit-message: >-
            Update ${{ matrix.key }} to ${{ steps.next.outputs.version }}
          branch: update-dependency/${{ matrix.key }}
          delete-branch: true
          title: >-
            Update ${{ matrix.key }} to ${{ steps.next.outputs.version }}
          body: >
            This PR was created automatically to update
            ${{ matrix.key }} to ${{ steps.next.outputs.version }}.
          labels: |
            automation
            dependency-update
